<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'grade_pass_back' => [[], ['_controller' => 'App\\Controller\\GradePassBackController::index'], [], [['text', '/gradepassback']], [], []],
    'python' => [['chapter'], ['_controller' => 'App\\Controller\\PythonController::index'], [], [['variable', '/', '[^/]++', 'chapter', true], ['text', '/python']], [], []],
    'result' => [[], ['_controller' => 'App\\Controller\\ResultController::index'], [], [['text', '/result']], [], []],
    'root' => [[], ['_controller' => 'App\\Controller\\RootController::index'], [], [['text', '/']], [], []],
];
